framework:
    serializer:
        default_context:
            enable_max_depth: true
            circular_reference_limit: 1
            circular_reference_handler: 'App\Serializer\CircularHandler::handle'
